CREATE TABLE USER (
	ID BIGINT,
	USER_NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50),
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	PRIMARY KEY (ID),
	UNIQUE (USER_NAME)
);

CREATE SEQUENCE USER_ID_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 101 CACHE 20;

CREATE TABLE KUDOS (
	ID BIGINT,
	FROM_USER_ID BIGINT NOT NULL,
	TO_USER_ID BIGINT NOT NULL,
	AMOUNT TINYINT,
	MESSAGE VARCHAR(500),
	ENTRY_DTTM TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
);

CREATE SEQUENCE KUDOS_ID_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 101 CACHE 20;

CREATE TABLE ACTIVITY (
	ID BIGINT,
	KUDOS_ID BIGINT,
	FROM_USER_ID BIGINT,
	TO_USER_ID BIGINT,
	TYPE VARCHAR(50),
	COMMENT VARCHAR(50),
	ENTRY_DTTM TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
);

CREATE SEQUENCE ACTIVITY_ID_SEQ MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 101 CACHE 20;
