INSERT 
	INTO USER (ID, USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME)
	VALUES (1, 'apple', 'grannysmith', 'Al', 'Attson');
	
INSERT 
	INTO USER (ID, USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME) 
	VALUES (2, 'berry', 'straw', 'Barry', 'Beatson');

INSERT 
	INTO USER (ID, USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME)
	VALUES (3, 'catalina', 'winemixer', 'Catherine', 'Clarkson');
	
INSERT 
	INTO KUDOS (ID, FROM_USER_ID, TO_USER_ID, AMOUNT, MESSAGE)
	VALUES (1, 2, 3, 100, 'You suck!');
	
INSERT 
	INTO KUDOS (ID, FROM_USER_ID, TO_USER_ID, AMOUNT, MESSAGE)
	VALUES (2, 3, 1, 50, 'I hate you!');
	
INSERT 
	INTO ACTIVITY (ID, KUDOS_ID, FROM_USER_ID, TO_USER_ID, TYPE, COMMENT)
	VALUES (1, 1, 1, null, 'COMMENT', 'dido');
	
INSERT 
	INTO ACTIVITY (ID, KUDOS_ID, FROM_USER_ID, TO_USER_ID, TYPE, COMMENT)
	VALUES (2, null, 2, 3, 'FOLLOW', null);

INSERT 
	INTO ACTIVITY (ID, KUDOS_ID, FROM_USER_ID, TO_USER_ID, TYPE, COMMENT)
	VALUES (3, 2, 2, null, 'LIKE', null);
